# general settings
name: A05_Net_L_Haze_bs32p256
model_type: RestormerModel
scale: 1
num_gpu: 8
manual_seed: 123
padding_size: 64

# dataset and data loader settings
datasets:
  train:
    name: ITS
    type: DehazingImageDataset
    dataroot_gt: datasets/Dehaze/ITS/clear
    dataroot_lq: datasets/Dehaze/ITS/hazy
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: false

    gt_size: 256


  val_1:
    name: SOTS
    type: DehazingImageDataset
    dataroot_gt: datasets/Dehaze/SOTS/indoor/nyuhaze500/gt
    dataroot_lq: datasets/Dehaze/SOTS/indoor/nyuhaze500/hazy
    io_backend:
      type: disk


# network structures
network_g:
  type: XRestormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2,4,4,4]
  num_refinement_blocks: 4
  channel_heads: [1,2,4,8]
  spatial_heads: [1,2,4,8]
  overlap_ratio: [0.5,0.5,0.5,0.5]
  window_size: 8
  spatial_dim_head: 16
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  scale: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    # project: ~
    # resume_id: ~
    project: backbone
    resume_id:
    entity: xpixel-ntire2022

# dist training settings
dist_params:
  backend: nccl
  port: 29500
