# general settings
name: A11_MPRNet_SR_bs16p192
model_type: MPRNetModel
scale: 4
num_gpu: 8
manual_seed: 123
padding_size: 64

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/ClassicalSR/DF2K_LMDB/DF2K_train_HR_sub.lmdb
    dataroot_lq: datasets/ClassicalSR/DF2K_LMDB/DF2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: false

    gt_size: 192

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/ClassicalSR/Set5/GTmod4
    dataroot_lq: datasets/ClassicalSR/Set5/LRbicx4
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/ClassicalSR/Set14/GTmod4
    dataroot_lq: datasets/ClassicalSR/Set14/LRbicx4
    io_backend:
      type: disk
  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: /cpfs01/user/puyuandong/datasets/classicSR/Urban100/GTmod4
  #   dataroot_lq: /cpfs01/user/puyuandong/datasets/classicSR/Urban100/LRbicx4
  #   io_backend:
  #     type: disk


# network structures
network_g:
  type: MPRNet # all hyper-parameters are default in the original version
  in_c: 3
  out_c: 3
  n_feat: 58
  scale_unetfeats: 48
  scale_orsnetfeats: 32
  num_cab: 8
  kernel_size: 3
  reduction: 4
  bias: false
  scale: 4
# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    # project: ~
    # resume_id: ~
    project: backbone
    resume_id:
    entity: xpixel-ntire2022

# dist training settings
dist_params:
  backend: nccl
  port: 29500
